services:

  ember-feature-extraction-pipeline:
    image: ghcr.io/malware-concept-drift-detection/ember-features-extraction:master
    container_name: ember-feature-extraction-pipeline
    environment:
      MALWARE_DIR_PATH: /usr/input_data/malware/
      FINAL_DATASET_DIR: /usr/app/dataset/
      N_PROCESSES: 32
    volumes:
      - "/home/luca/WD/NortonDataset670/MALWARE/:/usr/input_data/malware/"
      - "./dataset/:/usr/app/dataset/"